POST http://localhost:3333/tasks
Content-Type: application/json

{
    "title": "Fix Corrigir bugs 4",
    "description": "Corrigir os bugs na aplicação"
}

###

GET http://localhost:3333/

###

GET http://localhost:3333/?search=Feat

###

PUT http://localhost:3333/tasks/cf107641-5d47-428f-818f-3975c67d4ef4
Content-Type: application/json

{
    "title": "Feat corrigir bugs 5 put",
    "description": "Corrigir os bugs na aplicação"
}

###

DELETE http://localhost:3333/tasks/cf107641-5d47-428f-818f-3975c67d4ef4
